<?php
/**
 * Sitemap Plugin
 * Sitemap configuration file.
 *
 * This file is used by the SitemapController to generate sitemaps from configuration array.
 * A configuration file is NOT required to make use of the Sitemap plugin.
 * Sitemaps can be generated by using the SitemapComponent alone as well!
 *
 * Types of sitemaps:
 * 'controller': List of controllers, which implement the SitemapInterface
 * 'model': List of models, which implement the SitemapBehavior
 * 'list': Generates sitemap from given list of urls
 *
 * A sitemap array:
 * [
 *  'url': Sitemap url
 *  'changefreq': Change-frequency of the URL contents. Defaults to monthly
 *  'priority': URL priority: 0 (low) - 1 (high). Defaults to 0.5
 *  'lastmodified': Date of last URL content modification. Defaults to null.
 * ]
 */
return [
    'Sitemap' => [
        'posts' => [
            'source' => 'model',
            'model' => 'Posts',
        ],
        'pages' => [
            'source' => 'controller',
            'controller' => 'Pages',
        ],
        'custom' => [
            'source' => 'list',
            'list' => []
        ],
    ]
];
